# Prometheus 설정 파일
global:
  scrape_interval: 15s  # 메트릭 수집 간격
  evaluation_interval: 15s  # 규칙 평가 간격

# 알림 규칙 (선택사항)
# rule_files:
#   - "alerts.yml"

scrape_configs:
  # PathFinder API 메트릭 수집
  - job_name: 'pathfinder-api'
    static_configs:
      - targets: ['api:8000']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Prometheus 자체 모니터링
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
